---
- name: Remove Opendistro Kibana package
  yum:
    name: "opendistroforelasticsearch-kibana"
    state: absent

- name: Remove official Kibana artifacts after package remove
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/kibana
    - /usr/share/kibana
    - /etc/kibana

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ opensearch_dashboards_components }}"
