---
- name: Wait for service
  wait_for:
    host: '{{ kibana_host }}'
    port: '{{ kibana_http_port }}'
    delay: 10
    timeout: 600

- name: Patch kibana bundle js file
  replace:
    path: "/usr/share/kibana/plugins/opendistroSecurityKibana/server/index.js"
    regexp: "If you have forgotten your username or password, please ask your system administrator"
    replace: "{{ kibana_bundle_js_patch }}"
  register: kibana_login_page
  when: not external_elasticsearch_readonly_username|length and not external_elasticsearch_readonly_password|length

- name: Patch kibana bundle js file
  replace:
    path: "/usr/share/kibana/plugins/opendistroSecurityKibana/server/index.js"
    regexp: "If you have forgotten your username or password, please ask your system administrator"
    replace: "Readonly user: {{ external_elasticsearch_readonly_username }} password: {{ external_elasticsearch_readonly_password }}"
  register: kibana_login_page
  when: external_elasticsearch_readonly_username|length and external_elasticsearch_readonly_password|length

- name: Validate if jwt token is valid
  block:
    - include_vars:
        file: /var/lib/software-factory/bootstrap-data/secrets.yaml
        name: elasticsearch_kibanauser_token

    - name: Making query with jwt header
      uri:
        url: "https://{{ fqdn }}/analytics_autologin/app/kibana_overview"
        method: GET
        headers:
          Authorization: "Bearer {{ elasticsearch_kibanauser_token }}"
        status_code: "200"
        validate_certs: true
  when: readonly_user_autologin | lower == 'jwt'

- name: Validate if basic auth is valid
  block:
    - include_vars:
        file: /var/lib/software-factory/bootstrap-data/secrets.yaml
        name: elasticsearch_kibanauser_basicauth

    - name: Making query with basicauth header
      uri:
        url: "https://{{ fqdn }}/analytics_autologin/app/kibana_overview"
        method: GET
        headers:
          Authorization: "Basic {{ elasticsearch_kibanauser_basicauth }}"
        status_code: "200"
        validate_certs: true
  when: readonly_user_autologin | lower == 'basic'

- name: Restart Kibana after changing login page
  systemd:
    name: kibana
    state: restarted
  when: kibana_login_page.changed
