---
- name: Check if Opensearch Dashboards user basicauth is in secrets
  command: grep -q 'opensearch_kibanauser_basicauth' /var/lib/software-factory/bootstrap-data/secrets.yaml
  delegate_to: "{{ install_server_host }}"
  register: _opensearch_dashboards_basicauth_old
  no_log: "{{ show_hidden_logs }}"
  ignore_errors: true

- name: Setup autologin for Basic auth
  block:
    - name: Gen Opensearch Dashboards basicauth when external
      block:
        - name: "Get user:password string for external opensearch user"
          set_fact:
            _opensearch_dashboards_basicauth_external_plain: "{{ external_opensearch_readonly_user }}:{{ external_opensearch_readonly_password }}"
        - name: Set encoded password string for external Opensearch dashboards user
          set_fact:
            _opensearch_dashboards_basicauth_external: "{{ _opensearch_dashboards_basicauth_external_plain | b64encode }}"
      when: external_opensearch_readonly_user is defined and external_opensearch_readonly_password is defined

    - name: Gen Opensearch Dashboards basicauth when internal
      block:
        - name: "Get user:password string for local Opensearch Dashboards user"
          set_fact:
            _opensearch_dashboards_basicauth_local_plain: "{{ opensearch_readonly_user }}:{{ opensearch_readonly_password }}"
        - name: Set encoded password string for local Opensearch Dashboards user
          set_fact:
            _opensearch_dashboards_basicauth_local: "{{ _opensearch_dashboards_basicauth_local_plain | b64encode }}"
      when: _opensearch_dashboards_basicauth_external is not defined

    - name: Set basicauth info
      set_fact:
        opensearch_kibanauser_basicauth: "{{ _opensearch_dashboards_basicauth_external | default(_opensearch_dashboards_basicauth_local) }}"

    - name: Copy basicauth in secrets.yaml
      lineinfile:
        path: /var/lib/software-factory/bootstrap-data/secrets.yaml
        regexp: "^opensearch_kibanauser_basicauth"
        line: "opensearch_kibanauser_basicauth: {{ opensearch_kibanauser_basicauth }}"
      delegate_to: "{{ install_server_host }}"

    - name: Add autologin include file
      template:
        src: opensearch_dashboards_autologin.conf.j2
        dest: /etc/httpd/conf.d/opensearch_dashboards_autologin.conf
        mode: "0444"
        owner: apache
        group: apache
      register: _opensearch_dashboards_autologin_httpd

    # NOTE: Handler is not restarting apache2 service before
    # other postjobs are done.
    - name: Restart httpd service without handler
      service:
        name: httpd
        state: restarted
      when: _opensearch_dashboards_autologin_httpd.changed

  when: readonly_user_autologin is defined and readonly_user_autologin | lower == 'basic' or _opensearch_dashboards_basicauth_old.rc == 1
