---
- name: Install requirements
  yum:
    name:
      - sf-web-assets
      - sf-docs
      - managesf-doc
      - httpd
      - mod_ssl
      - mod_wsgi
      - zuul-jobs-doc
      - sf-ui
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- name: Install keycloak-related dependencies
  yum:
    name:
      - mod_auth_openidc
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- name: Ensure /usr/share/zuul directory is present
  file:
    path: /usr/share/zuul
    state: directory
    owner: root
    mode: '0755'
  when: "'zuul' in roles"
