---
- name: Dump service logs
  shell: journalctl -u opensearch > {{ elk_log_dir }}/opensearch.log
  ignore_errors: true

- name: Fetch service logs
  synchronize:
    mode: pull
    src: "{{ elk_log_dir }}/"
    dest: "{{ log_dest }}/log"
  ignore_errors: true
