---
- name: Remove Opendistro package
  yum:
    name:
      - opendistroforelasticsearch
      - elasticsearch-oss
    state: absent

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ opensearch_components }}"
