---
- name: Remove official Logstash if it was earlier installed
  yum:
    name: logstash
    state: absent
  register: _official_logstash_package

- name: Remove official Logstash artifacts after package remove
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/logstash
    - /usr/share/logstash
    - /etc/logstash
  when: _official_logstash_package.changed

- name: Pull image - logstash
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ logstash_components }}"

- name: Pull image - curator
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ curator_components }}"
