---
- include_tasks: "{{ sf_tasks_dir }}/check_version.yml"
- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: logstash

- name: Create cert dir
  file:
    path: "{{ logstash_stack_certs }}"
    owner: logstash
    group: root
    state: directory

- name: Copy CA cert to logstash dir
  copy:
    src: "/var/lib/software-factory/bootstrap-data/certs/localCA.pem"
    dest: "{{ logstash_stack_certs }}/localCA.pem"
    mode: '0600'
    owner: logstash
    group: root
  when: not external_elasticsearch_cacert

- name: Configure external Elasticsearch
  block:
    - name: Check if Elasticsearch CA cert file exist
      stat:
        path: "{{ external_elasticsearch_cacert }}"
      register: _external_localca

    - name: Set global permission for cert
      file:
        path: "{{ external_elasticsearch_cacert }}"
        mode: '0644'
      when: _external_localca.stat.exists
  when: external_elasticsearch_cacert != "None"

- stat:
    path: /var/log/logstash/logstash.log
  register: logfile

- name: Create logstash.log
  file:
    path: /var/log/logstash/logstash.log
    owner: logstash
    group: logstash
  when: logfile.stat.exists

- name: Install configuration files
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.path | default('/etc/logstash') }}/{{ item.name }}"
  register: logstash_templates
  loop:
    - {name: 'curator.yml'}
    - {name: 'delete_old_indices.yml'}
    - {name: 'indexer.conf', path: '/etc/logstash/conf.d'}

- name: Configure jvm
  lineinfile:
    dest: /etc/logstash/jvm.options
    regexp: '^#?{{ item.regexp }}.*'
    line: '{{ item.line }}'
  loop:
    - regexp: '-Xms'
      line: '-Xms{{ logstash_minimum_heap_size }}'
    - regexp: '-Xmx'
      line: '-Xmx{{ logstash_maximum_heap_size }}'
  register: logstash_jvm_config

- name: Restart logstash if needed
  service:
    name: logstash
    state: restarted
  when: logstash_jvm_config.changed or logstash_templates.changed

- name: Enable logstash
  service:
    name: logstash
    enabled: "yes"
    state: started

- name: Setup delete old logstash indexes CRON
  cron:
    name: "Delete old logstash indexes"
    minute: 0
    hour: 0
    day: '*'
    job: "/bin/curator --config /etc/logstash/curator.yml /etc/logstash/delete_old_indices.yml"
