---
- name: Check {{ role_package }} configuration
  stat:
    path: "{{ gerritbot_config_dir }}/channels.yaml"
  register: dst_channels

- name: Check config-repo configuration
  shell: cat /root/config/{{ role_package }}/*.yaml > /root/config/{{ role_package }}/.channels.yaml
  changed_when: false

- name: Check config-repo merged file
  stat:
    path: /root/config/{{ role_package }}/.channels.yaml
  register: src_channels

- name: Update {{ role_package }} channels configuration
  when: dst_channels.stat.exists == false or dst_channels.stat.checksum != src_channels.stat.checksum
  command: cp /root/config/{{ role_package }}/.channels.yaml /etc/{{ role_package }}/channels.yaml

- name: Restart {{ role_package }}
  when: dst_channels.stat.exists == false or dst_channels.stat.checksum != src_channels.stat.checksum
  service:
    name: "{{ role_package }}"
    state: restarted
