---
- service_facts:
  run_once: true

- name: Stop the service
  service:
    name: "{{ role_package }}"
    state: stopped
  when: "'{{ role_package }}.service' in {{ ansible_facts.services }}"

- name: Remove {{ role_package }} rpm package
  yum:
    name: "{{ role_package }}"
    state: absent
  register: _remove_rpm_package

- name: Upgrade container
  include_role:
    name: sf-container
    tasks_from: upgrade.yaml
  loop: "{{ gerritbot_components }}"
