---
# Task to add a mapper to a client scope
#
# Inputs:
#
#   Variables:
#      addToclientScope - name of the client scope to add the mapper to
#      realm - name of the realm where the mapper will be added
#      name - name of the mapper to be added
#      protocol - protocol to be used by the mapper
#      consentRequired - When turned on, users see a consent page that they can use to grant access to that application.
#      protocolMapper - protocol to use between client-scope and mapper
#      config:
#          includedClientAudience - application client
#          idTokenClaim - default value true
#          accessTokenClaim - default value true
#
# This task adds a mapper to a client scope following the steps below:

# 1. Gets the client scope id from realm based of name
- name: Getting Client Scope {{ addToclientScope }} info
  command: >
    podman exec -it keycloak
    {{ keycloak_dir }}/bin/kcadm.sh get client-scopes
       --target-realm {{ keycloak_default_realm }}
       --fields name,id
       -q name={{ name }}
       {{ kcadm_options }}
  register: _client_scopes_id_results
  no_log: show_hidden_logs == False

# 2. Gets the client scope id associated with the client scope
- name: Getting client scope {{ addToclientScope }} id
  command: |
    python -c "
    import sys, json, re
    strconv = ' '.join( {{ _client_scopes_id_results.stdout_lines[1:] }})
    pattern = re.compile('id +: ([^ ]+) *, *name *: *([^ ,]+)')
    usersdict = {}
    for ( id, name ) in re.findall( pattern, strconv ):
       usersdict[name]=id
    print ( usersdict.get(\"{{ addToclientScope }}\") )
    "
  register: _cs_id
  failed_when: _cs_id.stdout == "None"
  no_log: show_hidden_logs == False

# 3. Adds the mapper to the client scope using the user id and realm name.
- name: "Create protocol mapper {{ name }} in client scope"
  command: >
    podman exec -it keycloak
    {{ keycloak_dir }}/bin/kcadm.sh create client-scopes/{{ _cs_id.stdout }}/protocol-mappers/models \
    --target-realm {{ keycloak_default_realm }}  \
    --set name={{ name }} \
    --set protocol={{ protocol }} \
    --set protocolMapper={{ protocolMapper }} \
    --set consentRequired={{ consentRequired }} \
    --set 'config."included.client.audience"={{ config.includedClientAudience }}' \
    --set 'config."included.custom.audience"={{ config.includedClientAudience }}' \
    --set 'config."id.token.claim"={{ config.idTokenClaim }}' \
    --set 'config."access.token.claim"={{ config.accessTokenClaim }}'
    {{ kcadm_options }}
  register: _mapper_created
  failed_when: _mapper_created.rc != 0 and not ( _mapper_created.stdout is search("mapper exists", multiline=True, ignorecase=True))
  no_log: show_hidden_logs == False

- name: "Add client scope to client {{ client_name }} defaults"
  command: >
    podman exec -it keycloak
    {{ keycloak_dir }}/bin/kcadm.sh update clients/{{ client_id }}/default-client-scopes/{{ _cs_id.stdout }} \
    --target-realm {{ keycloak_default_realm }}  \
    {{ kcadm_options }}
  register: _scope_added
  failed_when: _scope_added.rc != 0 and not ( _scope_added.stdout is search("already", multiline=True, ignorecase=True))
  no_log: show_hidden_logs == False
