---
- name: Disable services
  service:
    name: keycloak
    state: stopped
    enabled: "no"
  ignore_errors: "yes"

- block:
  - name: Delete containers
    include_role:
      name: sf-container
      tasks_from: delete.yaml
    loop: "{{ keycloak_components }}"
    when: item.dependencies_fulfilled | bool

  when: erase == True
