---
- name: Disable services
  service:
    name: "houndd"
    state: stopped
    enabled: "no"
  ignore_errors: true

- name: Remove packages
  yum:
    name: "{{ role_package }}"
    state: absent

- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ hound_repos_dir }}"
      when: sf_previous_version < 3.7

    - name: Delete containers
      include_role:
        name: sf-container
        tasks_from: delete.yaml
      loop: "{{ hound_components }}"

    - name: Remove {{ role_package }} data
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ hound_config_dir }}"
        - "{{ hound_repos_dir }}"

  when: erase == True
