---
- name: Ensure postfix group is present
  group:
    name: postfix
    state: present

- name: Ensure postfix user is present
  user:
    name: postfix
    group: postfix
    groups: mail
    state: present
    home: /var/spool/postfix
    shell: /sbin/nologin

- name: Set mailname
  copy:
    dest: /etc/mailname
    content: "{{ ansible_hostname }}.{{ fqdn }}"
    owner: root
    group: root
    mode: 0644

- name: Ensure directories exist
  file:
    owner: root
    group: root
    path: /etc/postfix/
    state: directory
    mode: 0755

- name: Manage main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart postfix

- name: Manage virtual file
  template:
    src: virtual.j2
    dest: /etc/postfix/virtual
    owner: root
    group: root
    mode: 0644
  register: postfix_virtual

- name: Generate virtual database
  shell: /usr/sbin/postmap /etc/postfix/virtual
  when: postfix_virtual is changed
  notify:
    - restart postfix

- name: Manage transport file
  template:
    src: transport.j2
    dest: /etc/postfix/transport
    owner: root
    group: root
    mode: 0644
  register: postfix_transport

- name: Generate virtual database
  shell: /usr/sbin/postmap /etc/postfix/transport
  when: postfix_transport is changed
  notify:
    - restart postfix

- name: Start service
  service:
    name: postfix
    enabled: "yes"
    state: started
