---
role_actions:
  - install
  - setup
  - backup
  - restore
  - get_logs
  - postconf
  - disable

role_package: kibana

owner: opensearch-dashboards
group: opensearch-dashboards
# NOTE: UID and GID was changed with commit:
# https://softwarefactory-project.io/r/c/containers/+/23475
uid: 10006
gid: 10006

opensearch_dashboards_components:
  - service: "opensearch-dashboards"
    os: "centos"
    image: "quay.rdoproject.org/software-factory/opensearch-dashboards:1.2.0-patched"
    digest: "sha256:0510c4dc0b2173a4f4d07466a6e7346d74a56fffd252ed41d469dccb1cbc62c5"
    mirror: ""
    skip-auto-update: true
    trigger_start: false
    params: >-
      --net host
      -v {{ elk_config_dir }}/certs/:/usr/share/opensearch/config/certs:Z
      -v {{ elk_config_dir }}/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:z

elk_config_dir: /etc/opensearch
elk_log_dir: /var/log/opensearch
old_kibana_config_dir: /etc/kibana

elasticsearch_http_port: 9200
elasticsearch_host: elasticsearch.example.com
elasticsearch_internal_url: "https://{{ elasticsearch_host }}:{{ elasticsearch_http_port }}"
elasticsearch_readonly_user: kibana
elasticsearch_readonly_password: "CHANGE_ME"

kibana_http_port: 5601
kibana_host: kibana.example.com
kibana_internal_url: "http://{{ kibana_host }}:{{ kibana_http_port }}"

kibana_bundle_js_patch: "Readonly user: {{ elasticsearch_readonly_user }} password: {{ elasticsearch_readonly_password }}"

keycloak_default_realm: SF

# External Elasticsearch configuration
external_elasticsearch_readonly_username: ''
external_elasticsearch_readonly_password: ''
