---
role_actions:
  - install
  - setup
  - backup
  - restore
  - get_logs
  - postconf
  - disable

role_package: kibana

owner: opensearch-dashboards
group: opensearch-dashboards
container_uid: 1000
container_gid: 1000

opensearch_dashboards_version: 1.2.0
opensearch_dashboards_container_version: "{{ opensearch_dashboards_version }}-1"

opensearch_dashboards_components:
  - service: "opensearch-dashboards"
    image: "quay.io/software-factory/opensearch-dashboards:{{ opensearch_dashboards_container_version }}"
    skip-auto-update: true
    params: >-
      --net host
      --user {{ container_uid }}:{{ container_gid }}
      --uidmap 0:4000:999
      --uidmap {{ container_uid }}:{{ opensearch_dashboard_uid | default(1000) }}:1
      -v {{ opensearch_dashboards_certs_dir }}:{{ opensearch_dashboards_container_certs_dir }}:z
      -v {{ elk_config_dir }}/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:z

elk_config_dir: /etc/opensearch
elk_log_dir: /var/log/opensearch
old_kibana_config_dir: /etc/kibana

opensearch_dashboards_certs_dir: "{{ elk_config_dir }}/certs/opensearch-dashboards"

opensearch_dashboards_container_dir: /usr/share/opensearch-dashboards
opensearch_dashboards_container_config_dir: "{{ opensearch_dashboards_container_dir }}/config"
opensearch_dashboards_container_certs_dir: "{{ opensearch_dashboards_container_config_dir }}/certificates"

elasticsearch_http_port: 9200
elasticsearch_host: elasticsearch.example.com
elasticsearch_internal_url: "https://{{ elasticsearch_host }}:{{ elasticsearch_http_port }}"
elasticsearch_readonly_user: kibana
elasticsearch_readonly_password: "CHANGE_ME"

kibana_http_port: 5601
kibana_host: kibana.example.com
kibana_internal_url: "http://{{ kibana_host }}:{{ kibana_http_port }}"

kibana_bundle_js_patch: "Readonly user: {{ elasticsearch_readonly_user }} password: {{ elasticsearch_readonly_password }}"

keycloak_default_realm: SF

# External Elasticsearch configuration
external_elasticsearch_readonly_username: ''
external_elasticsearch_readonly_password: ''

sf_cert_path: /var/lib/software-factory/bootstrap-data/certs
