---
- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/pki/ca-trust/source/anchors/localCA.pem

    - name: "Update trust"
      command: update-ca-trust

    - name: Remove packages
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - python2-pysflib
        - sf-config

    - name: "Remove Software Factory state data"
      file:
        path: "{{ item }}"
        state: 'absent'
      loop:
        - /usr/libexec/software-factory
        - /var/lib/software-factory/sql
        - /var/lib/software-factory/state
        - /var/lib/software-factory/versions
        - /var/lib/software-factory/.version
        - /var/lib/software-factory/bootstrap-data/secrets.yaml
  when: erase == True
