---
- block:
    - name: Remove old repos
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - centos-release-ceph-jewel
        - centos-release-openstack-pike
        - centos-release-opstools
      when: ansible_distribution == "CentOS"

    - name: Fix /usr/libexec mode
      file:
        path: /usr/libexec/software-factory
        owner: root
        group: root
        mode: "0755"
        state: directory
  when: sf_previous_version < 3.1

- block:
    # sf-3.2
    - name: Remove renamed files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/libexec/wait4port
        - /usr/libexec/wait4mariadb
        - /usr/libexec/wait4gerrit
        - /usr/local/bin/zuul-changes.py

    # sf-3.3
    - name: Remove unused openstack repos
      yum:
        name: "{{ item }}"
        state: absent
      loop:
        - centos-release-ceph-luminous
        - centos-release-openstack-queens
        - centos-release-qemu-ev
      when: ansible_distribution == "CentOS"

    # sf-3.3
    - name: Ensure invalid zuul public key are removed
      lineinfile:
        path: /var/lib/zuul/.ssh/known_hosts
        regexp: ".* (ecdsa-sha.*|ssh-ed25519) .*"
        state: absent
  when: sf_previous_version < 3.4

- block:
    # sf-3.6
    - name: Force packages reinstall (topmenu patches leftover removal)
      shell: rpm -q {{ item }} && yum reinstall -y {{ item }} || true
      loop:
        - etherpad
        - grafana
  when: sf_previous_version < 3.6

- block:
    # sf-4.0
    - name: Remove outdated packages
      yum:
        name:
          - repoxplorer
          - python3-cauth
          - python3-sfmanager
          - mod_auth_pubtkt
        state: absent
    - service:
        name: cauth
        enabled: false
        state: stopped
        daemon-reload: true
      ignore_errors: true
    - name: Remove cauth user
      user:
        name: cauth
        state: absent
        remove: true
      ignore_errors: true
    - name: Remove cauth related files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cauth
        - /etc/httpd/conf.d/cauth.site
        - /var/lib/cauth/keys/privkey.pem
        - /etc/httpd/conf.modules.d/00-tkt.conf
        - /etc/httpd/conf.d/auth_pubtkt.conf
        - /etc/httpd/conf.d/cauth.conf
        - /etc/httpd/saml2/idp_metadata.xml
  when: sf_previous_version < 3.8

- name: Remove conflicting packages
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - python-nose
    - centos-release-openshift-origin311
    - centos-release-ansible26
  when: ansible_distribution == "CentOS"
