---
- name: Disable services
  service:
    name: '{{ item }}'
    state: stopped
    enabled: "no"
  loop:
    - '{{ service_real_name }}'
    - '{{ role_package }}'
  ignore_errors: "yes"

- block:
    - name: "Check if {{ role_package }} container exists"
      command: "podman container exists {{ role_package }}"
      ignore_errors: yes
      register: _container_exists
      changed_when: no
      failed_when: _container_exists.rc not in [0, 1]
      become: true

    - name: Delete containers
      include_role:
        name: sf-container
        tasks_from: delete.yaml
      loop: "{{ influxdb_components }}"
      when: _container_exists.rc == 0

    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - '/etc/{{ role_package }}'
        - '/var/lib/{{ role_package }}'
        - '/var/log/{{ role_package }}'
        - "/etc/yum.repos.d/{{ influxdb_repo_name }}.repo"

    - name: Remove packages
      yum:
        name: '{{ item }}'
        state: absent
      loop:
        - '{{ role_package }}'
      when: _container_exists.rc != 0

  when: erase == True
