---
- name: Remove influxdb packages
  yum:
    name: "influxdb"
    state: absent

- name: Remove files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/yum.repos.d/{{ influxdb_repo_name }}.repo"

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ influxdb_components }}"
