---
role_actions:
  - stop
  - install
  - setup
  - backup
  - restore
  - update
  - get_logs
  - disable
  - postconf

role_package: "zuul"

old_owner: zuul
old_group: zuul

owner: opendev
group: opendev
uid: 10001
gid: 10001

patch_container_command: ""

zuul_components:
  - service: "zuul-executor"
    image: "quay.io/software-factory/zuul-executor:4.6.0"
    digest: "sha256:154f6216e1e41d3db0d9434e386309b3c1a494eb5182041c74f826882dff2a96"
    mirror: ""
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/lib/zuul/keys/:/var/lib/zuul/keys/:Z
      --volume /var/lib/zuul/.ssh/:/var/lib/zuul/.ssh/:Z
      --volume /var/lib/zuul/patches/:/var/lib/zuul/patches/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z
      --volume /var/lib/software-factory/ansible/ara/:/var/lib/software-factory/ansible/ara/:Z
      --privileged
    command: |
      apt update
      apt install python-dev gcc -y
      pushd /var/tmp/
      for pkg in managesf python-sfmanager; do
          git clone https://softwarefactory-project.io/r/software-factory/$pkg
          pushd $pkg
          pip3 install -r requirements.txt
          python3 setup.py install
          popd
      done
      # dhall
      curl -L -O https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-json-1.6.4-x86_64-linux.tar.bz2
      tar xf dhall-json-1.6.4-x86_64-linux.tar.bz2
      mv bin/* /usr/local/bin/
      # pypi
      python -m pip install ara==0.16.6
      python -m pip install grafyaml==0.0.8
      python -m pip install nodepool==4.1.0
      python -m pip install pynotedb==0.2.1
      # cleanup
      apt remove python-dev gcc -y
      apt clean
      rm -rf /var/tmp/{managesf,python-sfmanager}
  - service: "zuul-merger"
    image: "quay.io/software-factory/zuul-merger:4.6.0"
    digest: "sha256:fdcf741ef1dc65e7fc35c194966168d0a9a2c41f6d180969077c327243eaa85d"
    mirror: ""
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z
      --volume /var/lib/zuul/patches/:/var/lib/zuul/patches/:Z
      --privileged
  - service: "zuul-scheduler"
    image: "quay.io/software-factory/zuul-scheduler:4.6.0"
    digest: "sha256:a3cc5dc2435efa0cdadb7854f66ac259a7b309cef009e03ceff53ac5b57219aa"
    mirror: ""
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/lib/zuul/keys/:/var/lib/zuul/keys/:Z
      --volume /var/lib/zuul/.ssh/:/var/lib/zuul/.ssh/:Z
      --volume /var/lib/zuul/scripts/:/var/lib/zuul/scripts/:Z
      --volume /var/lib/zuul/patches/:/var/lib/zuul/patches/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z
  - service: "zuul-web"
    image: "quay.io/software-factory/zuul-web:4.6.0"
    digest: "sha256:f5dd164b0f7e43d1ec94a55f685d82ef29f6dfaef4693a96a83b4863b459b2f3"
    mirror: ""
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z
      --volume /var/lib/zuul/patches/:/var/lib/zuul/patches/:Z

zuul_services:
  - zuul-scheduler
  - zuul-merger
  - zuul-executor
  - zuul-web

zuul_scheduler_depends:
  - wait4service
  - zuul

zuul_conf_dir: "/etc/zuul"
zuul_lib_dir: "/var/lib/zuul"
zuul_log_dir: "/var/log/zuul"
zuul_share_dir: "/usr/share/javascript/zuul"

zuul_web_port: 9000
zuul_gearman_port: 4730

zuul_executor_ansible_setup_timeout: 60
zuul_executor_disk_limit: 1024
zuul_executor_load_multiplier: 2.5
zuul_executor_min_avail_hdd: 5.0
zuul_executor_min_avail_mem: 5.0

zuul_mysql_host: "mysql.example.com"
zuul_mysql_port: 3306
zuul_mysql_db: "zuul"
zuul_mysql_user: "zuul"
zuul_mysql_password: "CHANGE_ME"
zuul_hs256_secret: "CHANGE_ME"
zuul_keystore_secret: "CHANGE_ME"

gerrit_pub_url: "https://example.com/r/"
zuul_pub_url: "https://example.com/zuul/"

zuul_web_url: "http://localhost:{{ zuul_web_port }}"
zuul_ws_url: "ws://localhost:{{ zuul_web_port }}"

zuul_loglevel: INFO
zuul_root_loglevel: WARNING

# We need those variables to generate config-check nodepool.yaml file
nodepool_conf_dir: "/etc/nodepool"
nodepool_lib_dir: "/var/lib/nodepool"
nodepool_webapp_port: 8006

zuul_periodic_pipeline_mail_rcpt: root@localhost

elasticsearch_http_port: 9200
