---
role_actions:
  - stop
  - install
  - setup
  - backup
  - restore
  - update
  - get_logs
  - disable
  - postconf

role_package: "zuul"

old_owner: zuul
old_group: zuul

owner: opendev
group: opendev
uid: 10001
gid: 10001

patch_container_command: ""

zuul_version: "5.0.0"
zuul_container_version: "{{ zuul_version }}-0"

zuul_components:
  - service: "zuul-scheduler"
    image: "quay.io/software-factory/zuul-scheduler-ubi:{{ zuul_container_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/lib/zuul/executor/:/var/lib/zuul/executor/:Z
      --volume /var/lib/zuul/keys/:/var/lib/zuul/keys/:Z
      --volume /var/lib/zuul/.ssh/:/var/lib/zuul/.ssh/:Z
      --volume /var/lib/zuul/scripts/:/var/lib/zuul/scripts/:Z
      --volume /var/lib/zuul/tenant-secrets/:/var/lib/zuul/tenant-secrets/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z
  - service: "zuul-executor"
    image: "quay.io/software-factory/zuul-executor-ubi:{{ zuul_container_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/lib/zuul/keys/:/var/lib/zuul/keys/:Z
      --volume /var/lib/zuul/.ssh/:/var/lib/zuul/.ssh/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z
      --privileged
  - service: "zuul-merger"
    image: "quay.io/software-factory/zuul-merger-ubi:{{ zuul_container_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/lib/zuul/.ssh/:/var/lib/zuul/.ssh/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z
      --privileged
  - service: "zuul-web"
    image: "quay.io/software-factory/zuul-web-ubi:{{ zuul_container_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    params: >-
      --network host
      --volume /etc/zuul/:/etc/zuul/:Z
      --volume /var/log/zuul/:/var/log/zuul/:Z

zuul_services:
  - zuul-scheduler
  - zuul-merger
  - zuul-executor
  - zuul-web

zuul_scheduler_depends:
  - wait4service

zuul_conf_dir: "/etc/zuul"
zuul_lib_dir: "/var/lib/zuul"
zuul_log_dir: "/var/log/zuul"
zuul_share_dir: "/usr/share/javascript/zuul"

zuul_web_port: 9000

zuul_executor_ansible_setup_timeout: 60
zuul_executor_disk_limit: 1024
zuul_executor_load_multiplier: 2.5
zuul_executor_min_avail_hdd: 5.0
zuul_executor_min_avail_mem: 5.0

zuul_mysql_host: "mysql.example.com"
zuul_mysql_port: 3306
zuul_mysql_db: "zuul"
zuul_mysql_user: "zuul"
zuul_mysql_password: "CHANGE_ME"
zuul_hs256_secret: "CHANGE_ME"
zuul_keystore_secret: "CHANGE_ME"

gerrit_pub_url: "https://example.com/r/"
zuul_pub_url: "https://example.com/zuul/"

zuul_web_url: "http://localhost:{{ zuul_web_port }}"
zuul_ws_url: "ws://localhost:{{ zuul_web_port }}"

zuul_loglevel: INFO
zuul_root_loglevel: WARNING

# We need those variables to generate config-check nodepool.yaml file
nodepool_conf_dir: "/etc/nodepool"
nodepool_lib_dir: "/var/lib/nodepool"
nodepool_webapp_port: 8006

zuul_periodic_pipeline_mail_rcpt: root@localhost

elasticsearch_http_port: 9200
