---
- name: Disable service
  service:
    name: etherpad
    state: stopped
    enabled: "no"
  ignore_errors: "yes"

- block:
    - name: Remove files
      file:
        path: "{{ etherpad_lib_dir }}"
        state: absent

    - name: Remove packages
      yum:
        name: etherpad
        state: absent
  when: erase == True
