---
- name: Check container image version
  include_role:
    name: sf-container
    tasks_from: check_version.yaml
  loop: "{{ etherpad_components }}"

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: "{{ owner }}"
    home_dir: "{{ etherpad_lib_dir }}"

- name: Create container directory
  include_role:
    name: sf-container
    tasks_from: create_directory.yaml
  loop:
    - {path: "{{ etherpad_lib_dir }}", mode: "0755", recurse: "yes"}

- name: Apply selinux port labelling
  seport:
    ports: "{{ etherpad_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_virtualization_type not in ["podman", "systemd-nspawn"]
    - ansible_selinux.status == "enabled"

- name: "Setup settings.json"
  template:
    src: settings.json.j2
    dest: "{{ etherpad_lib_dir }}/settings.json"
  notify: [restart etherpad]

- name: Create container
  include_role:
    name: sf-container
    tasks_from: setup.yaml
  loop: "{{ etherpad_components }}"

- name: Start service
  systemd:
    name: etherpad
    state: started
    daemon_reload: "yes"
    enabled: "yes"
