---
- name: Getting container logs
  include_role:
    name: sf-container
    tasks_from: get_logs.yaml
  loop:
    - container: "logscraper"
      options: ""
      target: "{{ log_dest }}"
    - container: "logsender"
      options: ""
      target: "{{ log_dest }}"
