---
role_actions:
  - install
  - setup
  - disable
  - get_logs

role_package: logstash

elk_stack_version: 7
elk_sub_version: 10.2

owner: opensearch
group: opensearch
container_uid: 1000
container_gid: 1000

logstash_version: 7.10.1
logstash_container_version: "{{ logstash_version }}-1"

logstash_components:
  - service: "logstash"
    image: "quay.io/software-factory/logstash:{{ logstash_container_version }}"
    params: >-
      --net host
      --user {{ container_uid }}:{{ container_gid }}
      --uidmap 0:4000:999
      --uidmap {{ container_uid }}:{{ opensearch_uid | default(1000) }}:1
      -v {{ logstash_config_dir }}/logstash.yml:/usr/share/logstash/config/logstash.yml:z
      -v {{ logstash_config_dir }}/jvm.options:/usr/share/logstash/config/jvm.options:z
      -v {{ logstash_config_dir }}/conf.d:/usr/share/logstash/pipeline:z
      -v {{ logstash_stack_certs }}/localCA.pem:{{ logstash_stack_certs }}/localCA.pem:z
      -v {{ logstash_log_dir }}:/var/log/logstash:z

elasticsearch_http_port: 9200
elasticsearch_host: elasticsearch.example.com
elasticsearch_internal_url: "https://{{ elasticsearch_host }}:{{ elasticsearch_http_port }}"

logstash_config_dir: /etc/logstash
logstash_stack_certs: "{{ logstash_config_dir }}/certs"
logstash_index_dir: "{{ logstash_config_dir }}/conf.d"
logstash_log_dir: /var/log/logstash
logstash_host: logstash.example.com
logstash_input_port: '9999'
logstash_http_port: '9601'

logstash_retention_days: 60
zuul_retention_days: 180
logstash_maximum_heap_size: 512m
logstash_minimum_heap_size: 128m

# NOTE: Remove it after SF 3.8
curator_config_dir: "{{ logstash_config_dir }}/curator.d"
