---
role_actions:
  - install
  - setup
  - get_logs
  - disable

owner: logscraper
group: logscraper
container_gid: 1000
container_uid: 1000

opensearch_http_port: 9200
opensearch_host: opensearch.example.com

opensearch_logstash_password: "CHANGE_ME"

zuul_api_url: https://{{ fqdn }}/zuul/api/tenant/local
insecure: false
download: true
logscraper_dir: /var/lib/logscraper
download_dir: /var/lib/logscraper/local
checkpoint_file: "{{ logscraper_dir }}/checkpoint"
file_list: "{{ logscraper_dir }}/download-list.yaml"
max_skipped: 1000
debug: false
logscraper_wait_time: 120
logscraper_workers: 2
# logsender
es_host: ""
es_port: ""
es_logstash_username: "logstash"
es_logstash_password: "{{ opensearch_logstash_password }}"
es_index_prefix: "logstash-"
es_insecure: false
logsender_workers: 2
logsender_wait_time: 60
custom_ca_crt: "/etc/opensearch/certs/opensearch/localCA.pem"

log_processing_components:
  - service: "logscraper"
    image: "quay.io/software-factory/logscraper:latest"
    skip-auto-update: true
    params: >-
      --net host
      --user {{ container_uid }}:{{ container_gid }}
      --uidmap 0:4000:999
      --uidmap {{ container_uid }}:{{ logscraper_uid | default(1000) }}:1
      --volume {{ logscraper_dir | default(logscraper_dir) }}:{{ logscraper_dir }}:z
      --volume {{ download_dir }}:{{ download_dir }}:z
      --volume {{ checkpoint_file }}:{{ checkpoint_file }}:z
      {% if external_opensearch_cacert and external_opensearch_cacert != '' %}
      --volume {{ external_opensearch_cacert }}:{{ external_opensearch_cacert }}:z
      {% else %}
      --volume {{ custom_ca_crt }}:{{ custom_ca_crt }}:z
      {% endif %}
      {% if sf_logscraper_additional_params is defined %}
      {{ sf_logscraper_additional_params }}
      {% endif %}
    run: >-
      /usr/local/bin/logscraper
      --config {{ logscraper_dir }}/logscraper.yaml
  - service: "logsender"
    image: "quay.io/software-factory/logscraper:latest"
    skip-auto-update: true
    params: >-
      --net host
      --user {{ container_uid }}:{{ container_gid }}
      --uidmap 0:4000:999
      --uidmap {{ container_uid }}:{{ logscraper_uid | default(1000) }}:1
      --volume {{ download_dir }}:{{ download_dir }}:z
      --volume {{ logscraper_dir }}:{{ logscraper_dir }}:z
      {% if external_opensearch_cacert and external_opensearch_cacert != '' %}
      --volume {{ external_opensearch_cacert }}:{{ external_opensearch_cacert }}:z
      {% else %}
      --volume {{ custom_ca_crt }}:{{ custom_ca_crt }}:z
      {% endif %}
      {% if sf_logsender_additional_params is defined %}
      {{ sf_logsender_additional_params }}
      {% endif %}
    run: >-
      /usr/local/bin/logsender
      --config {{ logscraper_dir }}/logsender.yaml
