---
role_actions:
  - install
  - setup
  - disable
  - get_logs

role_package: lodgeit

container_uid: 1000
container_gid: 1000
owner: "{{ role_package }}"
group: "{{ role_package }}"

lodgeit_port: 5000
lodgeit_mysql_host: "mysql.example.com"
lodgeit_mysql_port: 3306
lodgeit_mysql_db: "lodgeit"
lodgeit_mysql_user: "lodgeit"
lodgeit_mysql_password: "CHANGE_ME"

lodgeit_session_key: "CHANGE_ME"

lodgeit_container_web_resources : "/usr/local/lib/python3.8/site-packages/lodgeit/static"
lodgeit_web_resources : "/var/www/static/lodgeit"

lodgeit_version: 0.3
lodgeit_container_version: "{{ lodgeit_version }}-1"

lodgeit_components:
  - service: "{{ role_package }}"
    image: "quay.io/software-factory/{{ role_package }}:{{ lodgeit_container_version }}"
    params: >-
      --network host
      --uidmap 0:4000:999
      --uidmap {{ container_uid }}:{{ lodgeit_uid | default(1000)}}:1
      --env LODGEIT_SECRET_KEY={{ lodgeit_session_key }}
      --env LODGEIT_DBURI=mysql+pymysql://{{ lodgeit_mysql_user }}:{{ lodgeit_mysql_password }}@{{ lodgeit_mysql_host }}:{{ lodgeit_mysql_port }}/{{ lodgeit_mysql_db }}
      --env UWSGI_HTTP_SOCKET=:{{ lodgeit_port }}
