---
- service_facts:
  run_once: true

- block:
    - name: Stop the service
      service:
        name: "{{ role_package }}"
        state: stopped

    - name: Remove {{ role_package }} rpm package
      yum:
        name: "{{ role_package }}"
        state: absent
  when: "'{{ role_package }}.service' in {{ ansible_facts.services }}"

- name: Upgrade container
  include_role:
    name: sf-container
    tasks_from: upgrade.yaml
  loop: "{{ murmur_components }}"
