---
role_actions:
  - install
  - setup
  - disable
  - get_logs

role_package: logserver

container_uid: 1000
container_gid: 1000
owner: "loguser"
group: "loguser"

logserver_authorized_keys: []

# 2 months log expiry
logs_expiry: 60

logs_directory_prefix: logs/
# wsgi configuration
logs_wsgi_processes: 8
logs_wsgi_threads: 1
logs_wsgi_ara_directory: ara-report
logs_wsgi_ara_tmpdir_max_age: 3600
logs_wsgi_ara_logdir: /var/www

logserver_version: 4.9.3
logserver_container_version: "{{ logserver_version }}-1"

purgelogs_version: 0.2.0

logserver_port: 31215

logserver_config_dir: /etc/logserver
logserver_httpd_cont_conf_file: "logserver.conf"
logserver_httpd_proxy_file: "logserverproxy.conf"

logserver_components:
  - service: "purgelogs"
    image: "quay.io/software-factory/purgelogs:{{ purgelogs_version }}"
    params: >-
      --volume /var/www/:/var/www/:Z
    run: >-
      bash -c "/usr/local/bin/purgelogs --retention-days '{{ logs_expiry }}' --loop 3600 --log-path-dir /var/www/logs"

  - service: "{{ role_package }}"
    image: "quay.io/software-factory/{{ role_package }}:{{ logserver_container_version }}"
    params: >-
      --network host
      --tty
      --uidmap 0:4000:999
      --gidmap 0:4000:999
      --uidmap {{ container_uid}}:{{ logserver_uid | default(1000) }}:1
      --gidmap {{ container_gid }}:{{ logserver_gid | default(1000) }}:1
      --volume {{ logserver_config_dir }}/{{ logserver_httpd_cont_conf_file }}:/etc/httpd/conf.d/{{ logserver_httpd_cont_conf_file }}:Z
      --volume /var/www/:/var/www/:Z
