---
- name: Set podman command facts
  set_fact:
    podman_command: "podman exec {{ role_package }}"

- name: "Get database list"
  shell: >
    {{ podman_command }} sh -c ' mysql
    -uroot -p$MYSQL_ROOT_PASSWORD
    -ANe "SELECT schema_name FROM information_schema.schemata
    WHERE schema_name NOT IN
    (\"mysql\",\"information_schema\",\"performance_schema\")"' | tr '\n' ' '
  register: dblist

- name: "Ensure {{ role_package }} is started"
  service:
    name: "{{ role_package }}"
    enabled: "yes"
    state: started

- name: "Dump database locally"
  shell: >
    {{ podman_command }} sh -c ' mysqldump
    -uroot -p$MYSQL_ROOT_PASSWORD
    --databases {{dblist.stdout}}' | gzip -9 > {{ backup_dest }}/mysqldump.sql.gz
