---
- name: Install requirements
  yum:
    name:
      - MySQL-python
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- name: Remove packages
  yum:
    name:
      - mariadb-server
    state: absent
    autoremove: true
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
  register: _remove_mariadb_server

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: "{{ owner }}"

- name: "Get {{ owner }} uid"
  command: "id -u {{ owner }}"
  register: _user_id

- name: "Get {{ owner }} gid"
  command: "id -g {{ owner }}"
  register: _usergroup_gid

- name: "Setting {{ owner }} vars"
  set_fact:
    user_uid: "{{ _user_id.stdout }}"
    usergroup_gid: "{{ _usergroup_gid.stdout }}"

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ mysql_components }}"
