---
role_actions:
  - install
  - setup
  - update
  - upgrade
  - get_logs
  - disable
  - postconf

role_package: "nodepool"

old_owner: nodepool
old_group: nodepool

owner: opendev
group: opendev
uid: 10001
gid: 10001

dib_upstream_elements: True

nodepool_container_version: 4.3.0-2

nodepool_version: "4.3.0"

nodepool_services:
  - nodepool-launcher
  - nodepool-builder

nodepool_cache_ttl: 5
nodepool_providers:
  - name: default
    api_timeout: 60
    auth_url: http://localhost:35357/v2.0
    project_name: tenantname
    username: username
    password: secret
    region_name: regionOne

nodepool_components:
  - service: "nodepool-launcher"
    image: "quay.io/software-factory/nodepool-launcher-ubi:{{ nodepool_container_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    run: >-
      su --login nodepool
      -c ". /var/lib/nodepool/nodepool-env && /usr/local/bin/nodepool-launcher -d
      -c /etc/nodepool/nodepool.yaml
      -s /etc/nodepool/secure.conf
      -l /etc/nodepool/launcher-logging.yaml"
    params: >-
      --network host
      --volume /etc/nodepool/:/etc/nodepool/:Z
      --volume /var/lib/nodepool/:/var/lib/nodepool/:Z
      --volume /var/log/nodepool/:/var/log/nodepool/:Z
      --volume /var/www/html/nodepool-launcher/:/var/www/html/nodepool-launcher/:Z
  - service: "nodepool-builder"
    image: "quay.io/software-factory/nodepool-builder-ubi:{{ nodepool_container_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    run: >-
      su --login nodepool
      -c ". /var/lib/nodepool/nodepool-env && /usr/local/bin/nodepool-builder -d
      -c /etc/nodepool/nodepool.yaml
      -s /etc/nodepool/secure.conf
      -l /etc/nodepool/builder-logging.yaml"
    params: >-
      --network host
      --volume /dev:/dev
      --volume /run/libvirt:/run/libvirt
      --volume /etc/nodepool/:/etc/nodepool/:Z
      --volume /usr/bin/dib-virt-customize:/usr/bin/dib-virt-customize
      --volume /usr/share/sf-elements/:/usr/share/sf-elements/
      --volume /var/cache/nodepool/:/var/cache/nodepool/:Z
      --volume /var/lib/nodepool/:/var/lib/nodepool/:Z
      --volume /var/log/nodepool/:/var/log/nodepool/:Z
      --volume /var/www/html/nodepool-builder/:/var/www/html/nodepool-builder/:Z
      {% if dib_upstream_elements %}
      --volume /usr/share/project-config/:/usr/share/project-config/
      {% endif %}
      --privileged

nodepool_cache_dir: "/var/cache/nodepool"
nodepool_conf_dir: "/etc/nodepool"
nodepool_html_builder_dir: "/var/www/html/nodepool-builder"
nodepool_html_launcher_dir: "/var/www/html/nodepool-launcher"
nodepool_lib_dir: "/var/lib/nodepool"
nodepool_log_dir: "/var/log/nodepool"

nodepool_webapp_port: 8006

nodepool_loglevel: INFO
nodepool_root_loglevel: WARNING

nodepool_build_log_retention: 7

nodepool_openshift_providers: []
nodepool_kube_file: ""
nodepool_aws_file: ""
