---
role_actions:
  - install
  - setup
  - update
  - upgrade
  - get_logs
  - disable
  - postconf

role_package: "nodepool"

old_owner: nodepool
old_group: nodepool

owner: opendev
group: opendev
uid: 10001
gid: 10001

dib_upstream_elements: True

patch_container_command: |
  apt update
  apt install patch -y
  pushd /usr/local/lib/python3.7/site-packages
  for patch in $(ls /var/lib/nodepool/patches/*patch); do
      patch -p1 < $patch
  done
  popd

nodepool_version: "4.3.0"

nodepool_services:
  - nodepool-launcher
  - nodepool-builder

nodepool_cache_ttl: 5
nodepool_providers:
  - name: default
    api_timeout: 60
    auth_url: http://localhost:35357/v2.0
    project_name: tenantname
    username: username
    password: secret
    region_name: regionOne

nodepool_components:
  - service: "nodepool-launcher"
    image: "quay.io/software-factory/nodepool-launcher:{{ nodepool_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    os: "debian"
    run: >-
      su --login nodepool
      -c ". /var/lib/nodepool/nodepool-env && /usr/local/bin/nodepool-launcher -d
      -c /etc/nodepool/nodepool.yaml
      -s /etc/nodepool/secure.conf
      -l /etc/nodepool/launcher-logging.yaml"
    params: >-
      --network host
      --volume /etc/nodepool/:/etc/nodepool/:Z
      --volume /var/lib/nodepool/:/var/lib/nodepool/:Z
      --volume /var/log/nodepool/:/var/log/nodepool/:Z
      --volume /var/www/html/nodepool-launcher/:/var/www/html/nodepool-launcher/:Z
    command: |
      apt update
      apt install git curl bzip2 python-dev gcc -y
      pushd /var/tmp/
      for pkg in managesf python-sfmanager; do
          git clone https://softwarefactory-project.io/r/software-factory/$pkg
          pushd $pkg
          pip3 install -r requirements.txt
          python3 setup.py install
          popd
      done
      # dhall
      curl -L -O https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-json-1.6.4-x86_64-linux.tar.bz2
      tar xf dhall-json-1.6.4-x86_64-linux.tar.bz2
      mv bin/* /usr/local/bin/
      # certs
      find /var/lib/nodepool/certs/ -type f -exec cp {} /usr/local/share/ca-certificates/ \;
      update-ca-certificates
      # cleanup
      apt remove git curl bzip2 python-dev gcc -y
      apt clean
      rm -rf /var/tmp/{managesf,python-sfmanager}
  - service: "nodepool-builder"
    image: "quay.io/software-factory/nodepool-builder:{{ nodepool_version }}"
    mirror: ""
    stopped: True
    skip-auto-update: True
    os: "debian"
    run: >-
      su --login nodepool
      -c ". /var/lib/nodepool/nodepool-env && /usr/local/bin/nodepool-builder -d
      -c /etc/nodepool/nodepool.yaml
      -s /etc/nodepool/secure.conf
      -l /etc/nodepool/builder-logging.yaml"
    params: >-
      --network host
      --volume /dev:/dev
      --volume /run/libvirt:/run/libvirt
      --volume /etc/nodepool/:/etc/nodepool/:Z
      --volume /usr/bin/dib-virt-customize:/usr/bin/dib-virt-customize
      --volume /usr/share/sf-elements/:/usr/share/sf-elements/
      --volume /var/cache/nodepool/:/var/cache/nodepool/:Z
      --volume /var/lib/nodepool/:/var/lib/nodepool/:Z
      --volume /var/log/nodepool/:/var/log/nodepool/:Z
      --volume /var/www/html/nodepool-builder/:/var/www/html/nodepool-builder/:Z
      {% if dib_upstream_elements %}
      --volume /usr/share/project-config/:/usr/share/project-config/
      {% endif %}
      --privileged
    command: |
      apt update
      apt install git curl bzip2 python-dev gcc -y
      pushd /var/tmp/
      for pkg in managesf python-sfmanager; do
          git clone https://softwarefactory-project.io/r/software-factory/$pkg
          pushd $pkg
          pip3 install -r requirements.txt
          python3 setup.py install
          popd
      done
      # dhall
      curl -L -O https://github.com/dhall-lang/dhall-haskell/releases/download/1.32.0/dhall-json-1.6.4-x86_64-linux.tar.bz2
      tar xf dhall-json-1.6.4-x86_64-linux.tar.bz2
      mv bin/* /usr/local/bin/
      # nodepool-builder depends
      apt install -y ansible libguestfs-tools git
      # Update diskimage-builder
      pip install --upgrade diskimage-builder
      # certs
      find /var/lib/nodepool/certs/ -type f -exec cp {} /usr/local/share/ca-certificates/ \;
      update-ca-certificates
      # cleanup
      apt remove python-dev gcc -y
      apt clean
      rm -rf /var/tmp/{managesf,python-sfmanager}

nodepool_cache_dir: "/var/cache/nodepool"
nodepool_conf_dir: "/etc/nodepool"
nodepool_html_builder_dir: "/var/www/html/nodepool-builder"
nodepool_html_launcher_dir: "/var/www/html/nodepool-launcher"
nodepool_lib_dir: "/var/lib/nodepool"
nodepool_log_dir: "/var/log/nodepool"

nodepool_webapp_port: 8006

nodepool_loglevel: INFO
nodepool_root_loglevel: WARNING

nodepool_build_log_retention: 7

nodepool_openshift_providers: []
nodepool_kube_file: ""
nodepool_aws_file: ""
