---
- name: Remove package
  yum:
    name: "{{ role_package }}"
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ mosquitto_components }}"
