---
- name: "Stop {{ role_package }} container service"
  service:
    name: "{{ role_package }}"
    state: stopped

- name: Upgrade container
  include_role:
    name: sf-container
    tasks_from: upgrade.yaml
  loop: "{{ mosquitto_components }}"
