---
- name: restart opensearch
  systemd:
    name: opensearch
    state: restarted
    daemon_reload: true

- name: ensure started opensearch
  systemd:
    name: opensearch
    state: started
    enabled: "yes"

- name: wait for opensearch service
  uri:
    url: "{{ elasticsearch_internal_url }}"
    method: GET
    validate_certs: false
    status_code: "401"
  register: _opensearch_service_status
  until: "(_opensearch_service_status is successful) and (_opensearch_service_status.status == 401)"
  retries: 30
  delay: 10

- name: reconfigure security plugin in containers
  command: /usr/local/bin/reconfigure-opensearch.sh
