---
- name: Disable services
  service:
    name: opensearch
    state: stopped
    enabled: false
  ignore_errors: true

- block:
    - name: Delete containers
      include_role:
        name: sf-container
        tasks_from: delete.yaml
      loop: "{{ opensearch_components }}"

  when: erase == True
