---
- name: Set OpenSearch users as a fact - internal user
  set_fact:
    "opensearch_{{ item.key }}": "{{ item.value.password }}"
    "opensearch_{{ item.key }}_hash": "{{  item.value.password | password_hash('bcrypt', rounds=12) }}"
  no_log: show_hidden_logs == False
