---
- name: Disable services
  service:
    name: 'grafana-server'
    state: stopped
    enabled: "no"
  ignore_errors: "yes"

- name: Delete container - grafana
  include_role:
    name: sf-container
    tasks_from: delete.yaml
  loop: "{{ grafana_components }}"

- block:
    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - '/etc/{{ service_name }}'
        - '/var/lib/{{ service_name }}'
        - '/var/log/{{ service_name }}'
        - "/etc/yum.repos.d/{{ grafana_repo_name }}.repo"
        - '/etc/grafyaml'
        - '/var/run/grafana'
        - '{{ grafyaml_metrics }}'
        - '/usr/bin/update-grafana-graphs.sh'
      ignore_errors: "yes"

    - name: Remove packages
      yum:
        name: '{{ item }}'
        state: absent
      loop:
        - '{{ service_name }}'
        - 'grafyaml'
  when: erase == True
