---
- name: Check if CentOS system
  set_fact:
    extra_repos: "base,updates"
  when: ansible_distribution == "CentOS"

- name: Check if RedHat system
  set_fact:
    extra_repos: "rhel-7-server-rpms"
  when: ansible_distribution == "RedHat"

- name: Remove grafana package
  yum:
    name: grafana
    state: absent

- name: Install grafyaml for config-update and config-check
  yum:
    name: grafyaml
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
  delegate_to: "{{ item }}"
  loop: "{{ executor_hosts | union( groups['install-server'] ) }}"

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: "{{ owner }}"

- name: Get {{ owner }} uid
  command: id -u {{ owner }}
  register: _grafana_id

- name: Setting {{ owner }} uid var
  set_fact:
    grafana_uid: "{{ _grafana_id.stdout }}"

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ grafana_components }}"

