---
- name: Check if CentOS system
  set_fact:
    extra_repos: "base,updates"
  when: ansible_distribution == "CentOS"

- name: Check if RedHat system
  set_fact:
    extra_repos: "rhel-7-server-rpms"
  when: ansible_distribution == "RedHat"

- name: check if grafana package is present
  command: rpm -ql grafana
  register: _grafana_package
  changed_when: false
  failed_when: false
  args:
    warn: false

- name: Stop grafana-server service
  systemd:
    name: grafana-server
    state: stopped
  when: _grafana_package.rc == 0

- name: Remove grafana package
  yum:
    name:
      - grafana
      - grafyaml
    state: absent

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: _grafana_package.rc == 0

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: "{{ owner }}"

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ grafana_components }}"
