---
- include_tasks: setup_config_repo.yml

- include_tasks: setup_sf_jobs.yml

- include_tasks: setup_zuul_jobs.yml
  when:
    - not zuul_upstream_zuul_jobs

# Ensure repo content template are updated
- include_tasks: update_config_repo.yml
- include_tasks: update_sf_jobs.yml
- include_tasks: update_zuul_jobs.yml
  when:
    - not zuul_upstream_zuul_jobs

- name: full reconfigure zuul
  shell: >-
    systemctl -q is-active zuul-scheduler
    && logger --tag sfconfig zuul full reconfigure
    && /usr/bin/podman exec -ti zuul-scheduler zuul-scheduler full-reconfigure
  register: _zuul_scheduler_exists
  failed_when: _zuul_scheduler_exists.rc not in [0, 3]
  delegate_to: "{{ zuul_scheduler_host }}"
  when: (change_pushed and not tenant_deployment) or update_fqdn

- include_tasks: provision_demo.yml
  when:
    - provision_demo
    - "'gerrit' in roles"

- name: Force config update when fqdn is updated
  shell: >-
    ansible-playbook /var/lib/software-factory/ansible/sf_configrepo_update.yml
  delegate_to: "{{ install_server_host }}"
  when: update_fqdn
