---
- name: Remove telegraf packages
  yum:
    name: "telegraf"
    state: absent

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ telegraf_components }}"
