---
- name: Stop the service
  service:
    name: "{{ role_package }}"
    state: stopped

- name: Remove {{ role_package }} rpm package
  yum:
    name: "{{ role_package }}"
    state: absent

- name: Upgrade container
  include_role:
    name: sf-container
    tasks_from: upgrade.yaml
  loop: "{{ telegraf_components }}"
