---
- name: Remove {{ role_package }} package
  yum:
    name: "{{ role_package }}"
    state: absent
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: zookeeper

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ zookeeper_components }}"
