---
# See https://issues.apache.org/jira/browse/ZOOKEEPER-3056
- name: Ensure snapshot exists
  file:
    path: "{{ zookeeper_lib_dir }}/snapshot.0"
    state: touch

- name: Check if {{ role_package }} is running
  command: systemctl is-active -q {{ role_package }}
  register: _zookeeper_service
  failed_when: _zookeeper_service.rc not in [0, 3]
  changed_when: false

- block:
    - name: Stop the service
      service:
        name: "{{ role_package }}"
        state: stopped

    - name: Remove {{ role_package }} rpm package
      yum:
        name: zookeeper
        state: absent
  when:
    - _zookeeper_service.rc == 0

- name: Upgrade container
  include_role:
    name: sf-container
    tasks_from: upgrade.yaml
  loop: "{{ zookeeper_components }}"
