---
role_actions:
  - disable
  - install
  - setup
  - get_logs

role_package: telegraf

container_uid: 1000
container_gid: 1000
owner: "{{ role_package }}"
group: "{{ role_package }}"

influxdb_host: influxdb.example.com
influxdb_port: 8086
telegraf_port: 8125
telegraf_influxdb_user: telegraf
telegraf_influxdb_password: CHANGE_ME

telegraf_version: 1.24.4
telegraf_container_version: "{{ telegraf_version }}-2"

telegraf_config_dir: /etc/telegraf

telegraf_components:
  - service: "{{ role_package }}"
    image: "quay.io/software-factory/telegraf:{{ telegraf_container_version }}"
    params: >-
      --network host
      --uidmap 0:4000:999
      --uidmap {{ container_uid }}:{{ telegraf_uid | default(1000) }}:1
      --volume {{ telegraf_config_dir }}:{{ telegraf_config_dir }}:Z
      --volume /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt
