---
role_actions:
  - install
  - setup
  - get_logs
  - postconf
  - disable

role_package: elasticsearch

owner: opensearch
group: opensearch
container_uid: 1000
container_gid: 1000

opensearch_version: 1.2.4
opensearch_container_version: "{{ opensearch_version }}-1"

opensearch_components:
  - service: "opensearch"
    image: "quay.io/software-factory/opensearch:{{ opensearch_container_version }}"
    skip-auto-update: true
    params: >-
      --net host
      --user {{ container_uid }}:{{ container_gid }}
      --uidmap 0:4000:999
      --uidmap {{ container_uid }}:{{ opensearch_uid | default(1000) }}:1
      -e DISABLE_INSTALL_DEMO_CONFIG=true
      -e "OPENSEARCH_JAVA_OPTS=-Xms{{ elasticsearch_minimum_heap_size }} -Xmx{{ elasticsearch_maximum_heap_size }}"
      -v {{ elk_data_dir }}:{{ opensearch_container_dir }}/data:z
      -v {{ elk_log_dir }}:{{ elk_log_dir }}:z
      -v {{ elk_stack_certs }}:{{ opensearch_container_certs_dir }}:z
      -v {{ elk_config_dir }}/config.yml:{{ opensearch_container_dir }}/plugins/opensearch-security/securityconfig/config.yml:z
      -v {{ elk_config_dir }}/opensearch.yml:{{ opensearch_container_config_dir }}/opensearch.yml:z
      -v {{ elk_config_dir }}/internal_users.yml:{{ opensearch_container_securityconfig_dir }}/internal_users.yml:z
      -v {{ elk_config_dir }}/roles_mapping.yml:{{ opensearch_container_securityconfig_dir }}/roles_mapping.yml:z
      -v {{ elk_config_dir }}/tenants.yml:{{ opensearch_container_securityconfig_dir }}/tenants.yml:z
      -v {{ elk_config_dir }}/roles.yml:{{ opensearch_container_securityconfig_dir }}/roles.yml:z
      -v {{ elk_config_dir }}/action_groups.yml:{{ opensearch_container_securityconfig_dir }}/action_groups.yml:z

opensearch_container_dir: /usr/share/opensearch
opensearch_container_config_dir: "{{ opensearch_container_dir }}/config"
opensearch_container_certs_dir: "{{ opensearch_container_config_dir }}/certificates"
opensearch_container_securityconfig_dir: "{{ opensearch_container_dir }}/plugins/opensearch-security/securityconfig"

elk_config_dir: /etc/opensearch
elk_data_dir: /var/lib/elasticsearch
elk_log_dir: /var/log/opensearch
elk_stack_certs: "{{ elk_config_dir }}/certs/opensearch"
old_elk_config_dir: /etc/elasticsearch
old_elk_stack_certs: "{{ old_elk_config_dir }}/certs"

elasticsearch_password: "CHANGE_ME"
elasticsearch_kibanaserver_password: "CHANGE_ME"
elasticsearch_logstash_password: "CHANGE_ME"
elasticsearch_zuul_password: "CHANGE_ME"
elasticsearch_readonly_user: kibana
elasticsearch_readonly_password: "CHANGE_ME"

elasticsearch_http_port: 9200
elasticsearch_host: elasticsearch.example.com
elasticsearch_internal_url: "https://{{ elasticsearch_host }}:{{ elasticsearch_http_port }}"

elasticsearch_maximum_heap_size: 512m
elasticsearch_minimum_heap_size: 128m
elasticsearch_replicas: 0

enable_performance_analyzer: false

keycloak_default_realm: SF
