---
role_actions:
  - install
  - setup
  - get_logs
  - postconf
  - disable

role_package: elasticsearch

owner: opensearch
group: opensearch
# NOTE: UID and GID was changed with commit:
# https://softwarefactory-project.io/r/c/containers/+/23475
# NOTE: uid 10003 is used by ara user and uid 10004 by loguser.
uid: 10005
gid: 10005

opensearch_version: 1.2.2
opensearch_container_version: "{{ opensearch_version }}-1"

opensearch_components:
  - service: "opensearch"
    image: "quay.io/software-factory/sf-opensearch:{{ opensearch_container_version }}"
    skip-auto-update: true
    trigger_start: false
    params: >-
      --net host
      --user 1000:1000
      --uidmap 0:1:999
      --uidmap 1000:{{ uid }}:1
      -e DISABLE_INSTALL_DEMO_CONFIG=true
      -e "OPENSEARCH_JAVA_OPTS=-Xms{{ elasticsearch_minimum_heap_size }} -Xmx{{ elasticsearch_maximum_heap_size }}"
      -v {{ elk_data_dir }}:/usr/share/opensearch/data:z
      -v {{ elk_log_dir }}:/var/log/opensearch:z
      -v {{ elk_config_dir }}/certs:/usr/share/opensearch/config/certs:Z
      -v {{ elk_config_dir }}/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:z
      -v {{ elk_config_dir }}/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml:z
      -v {{ elk_config_dir }}/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml:z
      -v {{ elk_config_dir }}/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml:z
      -v {{ elk_config_dir }}/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml:z
      -v {{ elk_config_dir }}/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml:z

elk_config_dir: /etc/opensearch
elk_data_dir: /var/lib/elasticsearch
elk_log_dir: /var/log/opensearch
elk_stack_certs: "{{ elk_config_dir }}/certs"
old_elk_config_dir: /etc/elasticsearch
old_elk_stack_certs: "{{ old_elk_config_dir }}/certs"

elasticsearch_password: "CHANGE_ME"
elasticsearch_kibanaserver_password: "CHANGE_ME"
elasticsearch_logstash_password: "CHANGE_ME"
elasticsearch_zuul_password: "CHANGE_ME"
elasticsearch_curator_password: "CHANGE_ME"
elasticsearch_readonly_user: kibana
elasticsearch_readonly_password: "CHANGE_ME"

elasticsearch_http_port: 9200
elasticsearch_host: elasticsearch.example.com
elasticsearch_internal_url: "https://{{ elasticsearch_host }}:{{ elasticsearch_http_port }}"

elasticsearch_maximum_heap_size: 512m
elasticsearch_minimum_heap_size: 128m
elasticsearch_replicas: 0

enable_performance_analyzer: false

keycloak_default_realm: SF
