---
- service_facts:
  run_once: true

- name: "Remove packages if {{ role_package }} is a container"
  block:
    - name: Stop services
      service:
        name: "httpd"
        state: stopped
        enabled: false

    - name: Removing Packages
      yum:
        name:
          - httpd
          - mod_wsgi
        state: absent
  when:
    - "'{{ role_package }}.service' in {{ ansible_facts.services }}"
    - "'gateway' not in roles"
    - "'cauth' not in roles"

- name: "Removing ara resources"
  block:
    - name: Stopping ara service
      service:
        name: "ara"
        state: stopped
        enabled: false

    - name: Deleting ara service file
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/ara.service
        - /srv/static/logs

    - name: Removing ara package
      yum:
        name:
          - ara
        state: absent

    - name: Deleting ara user
      user:
        name: ara
        state: absent
        remove: true

  when: "'ara.service' in {{ ansible_facts.services }}"

- name: Reloading Systemd
  systemd:
    daemon_reload: true

- name: Removing purgelogs package
  yum:
    name:
      - purgelogs
    state: absent

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ logserver_components }}"
