---
- name: Create user
  include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: "{{ owner }}"
    shell: /bin/sh

- name: "Restore data"
  synchronize:
    src: "{{ backup_src }}/"
    dest: /

- name: "Restore files ownership"
  file:
    path: "/var/www/logs"
    owner: "{{ owner }}"
    group: "{{ group }}"
    recurse: "yes"
    state: "directory"
