---
- name: "Fetch gerrit logs and config"
  synchronize:
    mode: pull
    src: "{{ item.dir }}"
    dest: "{{ log_dest }}/{{ item.dest }}/"
    rsync_opts:
       - "--exclude=mail"
       - "--exclude=ssh_host_*"
  loop:
    - dir: "/var/log/gerrit/"
      dest: "logs"
    - dir: "/etc/gerrit/"
      dest: "etc"
  ignore_errors: true
