---
- name: "Remove previous state and git repositories"
  file:
    path: "/var/lib/gerrit/{{ item }}"
    state: absent
  loop:
    - git
    - cache
    - index

- name: "Restore data"
  synchronize:
    src: "{{ backup_src }}/"
    dest: /

- name: "Restore ownership of directory {{ item }}"
  file:
    path: "{{ item }}"
    owner: "gerrit"
    group: "gerrit"
    recurse: "yes"
    state: directory
  loop:
    - /var/lib/gerrit/git
    - /var/lib/gerrit/.ssh

- name: "Restore ownership of file {{ item }}"
  file:
    path: "{{ item }}"
    owner: "gerrit"
    group: "gerrit"
    state: file
  loop:
    - /etc/gerrit/keystore

- name: "Ensure /var/lib/gerrit is owned by gerrit"
  file:
    path: /var/lib/gerrit
    owner: gerrit
    group: gerrit
    state: directory
