---
- name: Disable services
  service:
    name: "{{ role_package }}"
    state: stopped
    enabled: "no"
  ignore_errors: true

- block:

    - name: Delete containers
      include_role:
        name: sf-container
        tasks_from: delete.yaml
      loop: "{{ managesf_components }}"

    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ managesf_config_dir }}"
        - "{{ managesf_log_dir }}"
        - "{{ managesf_lib_dir }}"
        - /etc/httpd/managesf_htpasswd

    #TODO: This task should be removed when all
    # managesf services (managesf, managesf-resources, managesf-configuration)
    # are containerized
    - name: Remove packages
      yum:
        name: "{{ role_package }}"
        state: absent

  when: erase == True
