---
- name: "Fetch managesf logs"
  synchronize:
    mode: pull
    src: /var/log/managesf/
    dest: "{{ log_dest }}/log"
  ignore_errors: true

- name: "Fetch managesf config"
  synchronize:
    mode: pull
    src: "/etc/managesf/{{ item }}"
    dest: "{{ log_dest }}/{{ item }}"
  loop:
    - config.py
    - policy.yaml
  ignore_errors: true

- name: Getting container logs
  include_role:
    name: sf-container
    tasks_from: get_logs.yaml
  loop:
    - container: "{{ role_package }}"
      options: ""
      target: "{{ log_dest }}"
