---
- name: Remove managesf package
  yum:
    name: "{{ role_package }}"
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ executor_hosts | union( groups['managesf'] ) }}"

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ managesf_components }}"
