---
- name: "Stop {{ role_package }} container service"
  service:
    name: "{{ role_package }}"
    state: stopped

- name: Upgrade container
  include_role:
    name: sf-container
    tasks_from: upgrade.yaml
  loop: "{{ managesf_components }}"

- name: Try to update cache resources
  shell: |
    curl {{ managesf_internal_url }}/v2/resources > /var/www/api/resources.json.new
    mv /var/www/api/resources.json.new /var/www/api/resources.json
  delegate_to: "{{ gateway_host }}"
  failed_when: false
