---
- name: Disable services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: "no"
  loop: "{{ zuul_services }}"
  ignore_errors: "yes"

- name: Delete containers and files
  block:
    - name: Delete containers
      include_role:
        name: sf-container
        tasks_from: delete.yaml
      loop: "{{ zuul_components }}"
      when: item.service in zuul_services

    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/httpd/conf.d/zuul.conf
        - "{{ zuul_conf_dir }}"
        - "{{ zuul_lib_dir }}"
  when: erase == True
