---
- name: Check if /usr/libexec/software-factory/zuul-changes.py exists
  stat:
    path: /usr/libexec/software-factory/zuul-changes.py
  register: _dump_queues

- name: Write version in file
  copy:
    content: "{{ zuul_version }}"
    dest: "/var/lib/software-factory/versions/zuul"
  delegate_to: "{{ install_server_host }}"

- name: Dump zuul queues and remove zuul packages
  block:
    - name: Dump zuul queues
      command: >-
        /usr/libexec/software-factory/zuul-changes.py
        dump --dump_file /var/lib/software-factory/state/zuul-change-dump.sh

    - name: Stop zuul services
      systemd:
        name: "{{ item }}"
        state: stopped
      loop: "{{ zuul_services }}"

    - name: Remove zuul packages
      package:
        name:
          - ara
          - dhall
          - zuul
          - "{{ zuul_services }}"
        state: absent

    - name: Remove outdated scripts
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/libexec/software-factory/zuul-changes.py
        - /usr/libexec/software-factory/gearman-client
  when: _dump_queues.stat.exists

- name: Install scheduler depends
  yum:
    name: "{{ zuul_scheduler_depends }}"
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
  when: '"zuul-scheduler" in zuul_services'

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ zuul_components }}"
  when: item.service in zuul_services
