---
- name: "Restore data"
  synchronize:
    src: "{{ backup_src }}/"
    dest: /

- name: "Restore files ownership"
  file:
    path: "{{ item }}"
    owner: "{{ owner }}"
    group: "{{ owner }}"
    recurse: "yes"
    state: "directory"
  loop:
    - "{{ zuul_lib_dir }}/keys/"

- name: "Ensure /var/lib/zuul ownership"
  file:
    path: "{{ zuul_lib_dir }}"
    owner: "{{ owner }}"
    group: "{{ owner }}"
    state: directory
    mode: '0751'
