---
- include_tasks: "{{ sf_tasks_dir }}/check_version.yml"

- name: Create /etc/k1s directory
  file:
    path: /etc/k1s
    state: directory
    mode: 0700

- name: Install certificates
  no_log: true
  copy:
    content: "{{ item.content }}"
    dest: "/etc/k1s/{{ item.dest }}.pem"
    mode: '0400'
  loop:
    - content: "{{ k1s_crt }}"
      dest: "cert"
    - content: "{{ k1s_key }}"
      dest: "key"
    - content: "{{ k1s_chain }}"
      dest: "chain"

- name: Setup configuration
  no_log: true
  copy:
    content: |
      K1S_TOKEN={{ k1s_token }}
      K1S_TLS_PATH=/etc/k1s
    dest: /etc/sysconfig/k1s
    mode: '0400'

- name: Install service file
  ansible.builtin.copy:
    remote_src: true
    src: /usr/src/k1s-distgit/k1s.service
    dest: /etc/systemd/system/k1s.service

- name: Start service
  service:
    name: k1s
    state: started
    enabled: yes
    daemon-reload: true

- name: Add periodic job to prune unused podman images
  cron:
    name: "podman-image-prune"
    user: "root"
    minute: "0"
    hour: "2"
    job: 'podman image prune'
