---
- name: Disable service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: "no"
  loop: "{{ nodepool_services }}"
  ignore_errors: "yes"

- name: Delete containers and files
  block:
    - name: Delete containers
      include_role:
        name: sf-container
        tasks_from: delete.yaml
      loop: "{{ nodepool_components }}"
      when: item.service in nodepool_services

    - name: Remove files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/httpd/conf.d/nodepool_log.conf
        - /var/www/nodepool-log
        - "{{ nodepool_html_launcher_dir }}"
        - "{{ nodepool_lib_dir }}"
        - "{{ nodepool_conf_dir }}"
        - /root/.kube/config
  when: erase == True
