---
- name: Remove nodepool packages
  package:
    name:
      - dhall
      - nodepool
      - nodepool-builder
      - nodepool-launcher
    state: absent

# httpd to serve nodepool logs
- name: Install depends
  package:
    name:
      - httpd

# managesf for config update
- name: "Install managesf"
  ansible.builtin.pip:
    name:
      - managesf==0.32.1
    state: present

- name: Write version in file
  copy:
    content: "{{ nodepool_version }}"
    dest: "/var/lib/software-factory/versions/nodepool"
  delegate_to: "{{ install_server_host }}"

- name: Install packages for builder
  package:
    name:
      - libvirt-daemon
      - https://softwarefactory-project.io/kojifiles/repos/sf-3.8-el7-release/Mash/sf-elements-0.7.0-2.el7.noarch.rpm
  when: '"nodepool-builder" in nodepool_services'

- name: Install openshift client
  block:
    - name: Add repo for openshift-client
      copy:
        dest: /etc/yum.repos.d/microshift-deps.repo
        content: |
          [microshift-deps-rpms]
          name=Puddle of Microshift deps RPMs
          baseurl=https://mirror.openshift.com/pub/openshift-v4/$basearch/dependencies/rpms/4.13-el9-beta/
          enabled=0
          gpgcheck=0
          skip_if_unavailable=1

    - name: Install openshift-client
      ansible.builtin.package:
        name:
          - openshift-clients
        enablerepo: microshift-deps-rpms
  when: "nodepool_openshift_providers or nodepool_kube_file or 'hypervisor-k1s' in roles"

- include_tasks: "{{ sf_tasks_dir }}/create_user.yml"
  vars:
    user_name: "{{ owner }}"
    ssh_key: nodepool_rsa
    home_dir: "{{ nodepool_lib_dir }}"

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ nodepool_components }}"
  when: item.service in nodepool_services
