---
- name: Remove nodepool packages
  package:
    name:
      - dhall
      - nodepool
      - nodepool-builder
      - nodepool-launcher
    state: absent

# httpd to serve nodepool logs
# managesf for config update
- name: Install depends
  package:
    name:
      - httpd
      - managesf

- name: Install packages for builder
  package:
    name:
      - libvirt-daemon
      - sf-elements
  when: '"nodepool-builder" in nodepool_services'

- name: Pull image
  include_role:
    name: sf-container
    tasks_from: install.yaml
  loop: "{{ nodepool_components }}"
  when: item.service in nodepool_services

- name: Install openshift client
  block:
    - include_tasks: "{{ sf_tasks_dir }}/origin-311.yml"
      when: ansible_distribution == 'CentOS'

    - name: Install packages
      yum:
        name: '{{ openshift_client }}'
        state: present
  when: "nodepool_openshift_providers or nodepool_kube_file or 'hypervisor-k1s' in roles"
