---
- name: Remove legacy configuration file
  file:
    path: "{{ nodepool_conf_dir }}/{{ item }}-logging.conf"
    state: absent
  loop:
    - builder
    - launcher

- name: Remove unused packages
  package:
    name:
      - diskimage-builder
    state: absent

- name: Indicate nodepool needs to be restarted
  set_fact:
    nodepool_need_restart: true
