---
- name: "Install requirements"
  yum:
    name:
      - git
      - git-review
      - python-testinfra
      - zuul-jobs
      - rh-git218-git
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
