---
- job:
    name: demo-rpmbuild
    parent: base
    description: Build the demo-project rpm
    run: build-rpm.yaml
    required-projects:
      - demo-project
      - demo-project-distgit

- project:
    name: demo-project-distgit
    queue: demo-integrated
    check:
      jobs:
        - demo-rpmbuild
    gate:
      jobs:
        - demo-rpmbuild
